/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:936ca68d-55dc-4844-8c22-7970dfaf2ffc",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_CqWtJlQMK",
    "aws_user_pools_web_client_id": "5npi2tmmg05rjnosf3pmgq43tk",
    "oauth": {}
};


export default awsmobile;
